Use GitHub Actions for run tests
kaitai-io/kaitai_struct_compiler pull request #215
Opened 2020-11-19 19:22 UTC by Mingun

2020-11-19 21:13 UTC, generalmimon requested changes
Thanks for this contribution, it'd be nice to have it, but there are some issues:

2020-11-19 21:13 UTC, generalmimon commented on .github/workflows/scala.yml
> +        java-version: ${{matrix.java}}
I prefer to put spaces around the variables in GH Actions config, but that's just my personal preference:

```suggestion
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
```

2020-11-19 21:13 UTC, generalmimon commented on .github/workflows/scala.yml
> +      run: sbt test
I'm afraid that `sbt` does not come from the `actions/setup-java` action - searching for [`sbt` in its repo](https://github.com/actions/setup-java/search?q=sbt&type=code) found nothing.

2020-11-20 03:40 UTC, Mingun commented on .github/workflows/scala.yml
> +      run: sbt test
This is just default template that GitHub suggested me and I only was add several versions of java. I think, that template was manually written instead of auto-generated so it should work. I didn't get a chance to check if it is work, though

2020-11-20 04:05 UTC, Mingun commented on .github/workflows/scala.yml
> +      run: sbt test
I make a test and `sbt` already exists in the container:
https://github.com/Mingun/kaitai_struct_compiler/runs/1428552667

2020-11-20 04:12 UTC, Mingun commented on .github/workflows/scala.yml
> +name: Scala CI
Done

2020-11-20 04:13 UTC, Mingun commented on .github/workflows/scala.yml
> +        java-version: ${{matrix.java}}
Done

2020-11-21 08:36 UTC, Mingun commented
Is there any something that need to do? Otherwise its ready to merge

2020-11-21 08:42 UTC, generalmimon approved these changes
LGTM, thanks for the contribution!

2020-11-21 08:42 UTC, merged