Fix some broken TranslateSpec tests
kaitai-io/kaitai_struct_compiler pull request #228
Opened 2020-12-04 19:42 UTC by Mingun

It seems that the tests did not even run when making changes...

2020-12-17 18:54 UTC, Mingun commented
@GreyCat , @generalmimon this one seems easy to check -- I've found almost all commits that introduced bugs

2020-12-17 20:23 UTC, generalmimon requested changes

2020-12-17 20:23 UTC, generalmimon commented on jvm/src/test/scala/io/kaitai/struct/translators/TranslatorSpec.scala
> +    * @param src Kaitai struct expression to translate
```suggestion
    * @param src KS expression to translate
```

2020-12-17 20:23 UTC, generalmimon commented on jvm/src/test/scala/io/kaitai/struct/translators/TranslatorSpec.scala
> +                fail(s"no expected result, but result is ${tr.translate(e)}")
```suggestion
                fail(s"no expected result, but actual result is ${tr.translate(e)}")
```

2020-12-17 20:23 UTC, generalmimon commented on jvm/src/test/scala/io/kaitai/struct/translators/TranslatorSpec.scala
> +    * @param expOut Map with expected outputs of each language
```suggestion
    * @param expOut Map with expected outputs for each language
```

2020-12-17 20:23 UTC, generalmimon commented on jvm/src/test/scala/io/kaitai/struct/translators/TranslatorSpec.scala
> +    * @param expType Expected type that should be detected by translator
```suggestion
    * @param expType Expected type that should be detected by [[TypeDetector]]
```

2020-12-17 20:23 UTC, generalmimon commented on jvm/src/test/scala/io/kaitai/struct/translators/TranslatorSpec.scala
> -            val tr: AbstractTranslator with TypeDetector = langs(langObj)
It seems probably OK, but can you explain why did you delete this line?

2020-12-18 03:38 UTC, Mingun commented on jvm/src/test/scala/io/kaitai/struct/translators/TranslatorSpec.scala
> -            val tr: AbstractTranslator with TypeDetector = langs(langObj)
Just because `tr` already in scope from line 620

2020-12-18 12:23 UTC, generalmimon approved these changes
Looks good to me, thanks!

2020-12-18 12:23 UTC, merged