Implement `doByteArrayNonLiteral` for Lua and C++
kaitai-io/kaitai_struct_compiler pull request #281
Opened 2024-03-18 15:32 UTC by Mingun

2024-03-20 12:06 UTC, generalmimon requested changes

2024-03-20 16:09 UTC, Mingun commented on shared/src/main/scala/io/kaitai/struct/translators/LuaTranslator.scala
> +    "{" + values.map(translate).mkString(", ") + "}"
Ok, the Lua stuff was simple

2024-03-20 16:14 UTC, Mingun commented on shared/src/main/scala/io/kaitai/struct/translators/CppTranslator.scala
> +    doArrayLiteral(DataType.Int1Type(false), values)
Unfortunately, `doByteArrayLiteral` should produce an expression, but without initializer lists it is possible to use only statement to create a byte array ant then `std::string` from it:
```cpp
const char bytes[] = {
  (char)(mfg_id_ch1() + 0x40),
  (char)(mfg_id_ch2() + 0x40),
  (char)(mfg_id_ch3() + 0x40),
};
std::string(bytes, sizeof(bytes));
```
https://godbolt.org/z/e9YTxnWjE

Because anyway C++98 target is not fully implemented, I've implemented only `initializer_list` solution (so only since C++11).

2024-03-24 09:53 UTC, GreyCat commented on shared/src/main/scala/io/kaitai/struct/translators/CppTranslator.scala
> +      "std::string({" + values.map(value => s"char(${translate(value)})").mkString(", ") + "})"
`char(x)` is what's called [functional-style cast](https://en.cppreference.com/w/cpp/language/explicit_cast). It's not C-style cast, but it is equally implicit and can mean a lot of things.

I wonder if using `static_cast<char>(...)` will make more sense here?

2024-03-24 09:53 UTC, GreyCat approved these changes
Generally looks good, let's just close on whether we want `static_cast` or functional-style casts.

2024-03-24 09:56 UTC, GreyCat commented on shared/src/main/scala/io/kaitai/struct/translators/CppTranslator.scala
> +    doArrayLiteral(DataType.Int1Type(false), values)
In all fairness, there's nothing terribly wrong with getting our CppTranslator closer to GoTranslator in a sense that it might also use temporary variables allocated on stack to make things like that separate `const char bytes[] = { ... };` work for C++98. We already do that for Go, we will likely do that for C.

2024-03-30 08:36 UTC, Mingun commented on shared/src/main/scala/io/kaitai/struct/translators/CppTranslator.scala
> +    doArrayLiteral(DataType.Int1Type(false), values)
Indeed we should do that, but not in this PR

2024-03-30 08:46 UTC, Mingun commented on shared/src/main/scala/io/kaitai/struct/translators/CppTranslator.scala
> +      "std::string({" + values.map(value => s"char(${translate(value)})").mkString(", ") + "})"
Now `static_cast<char>(...)` is used

2024-03-30 08:54 UTC, GreyCat commented on jvm/src/test/scala/io/kaitai/struct/translators/TranslatorSpec.scala
> +        CppCompiler -> "std::string({char(0 + 1), char(5)})",
Looks like this test also needs to be updated

2024-03-30 09:16 UTC, Mingun commented on jvm/src/test/scala/io/kaitai/struct/translators/TranslatorSpec.scala
> +        CppCompiler -> "std::string({char(0 + 1), char(5)})",
Ah, yes... The consequence of permanently failing tests! Fixed

2024-03-30 09:40 UTC, generalmimon commented on shared/src/main/scala/io/kaitai/struct/translators/CppTranslator.scala
> +      throw new RuntimeException("C++ non-literal arrays are not implemented yet without list initializers")
```suggestion
      throw new RuntimeException("non-literal byte arrays are not implemented yet in C++98")
```

2024-03-30 09:40 UTC, generalmimon commented on shared/src/main/scala/io/kaitai/struct/translators/CppTranslator.scala
> +      throw new RuntimeException("C++ literal arrays are not implemented yet without list initializers")
```suggestion
      throw new RuntimeException("literal arrays are not implemented yet in C++98")
```

2024-03-30 10:17 UTC, Mingun commented on shared/src/main/scala/io/kaitai/struct/translators/CppTranslator.scala
> +      throw new RuntimeException("C++ non-literal arrays are not implemented yet without list initializers")
Applied

2024-04-05 16:06 UTC, Mingun commented
@generalmimon, what is your conclusion?

2024-10-02 23:35 UTC, generalmimon commented on shared/src/main/scala/io/kaitai/struct/translators/CppTranslator.scala
> +      throw new RuntimeException("C++ non-literal arrays are not implemented yet without list initializers")
Actually resolved in https://github.com/kaitai-io/kaitai_struct_compiler/pull/281/commits/208cf53a8ae6d81e9591152998770fc466b7e2ae

2024-10-02 23:35 UTC, generalmimon commented on shared/src/main/scala/io/kaitai/struct/translators/CppTranslator.scala
> +      throw new RuntimeException("C++ literal arrays are not implemented yet without list initializers")
Actually resolved in https://github.com/kaitai-io/kaitai_struct_compiler/commit/208cf53a8ae6d81e9591152998770fc466b7e2ae

2024-10-02 23:36 UTC, generalmimon approved these changes
@Mingun Thanks!

2024-10-02 23:36 UTC, merged